# Generated by Django 5.2.10 on 2026-02-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_options_bookinstance_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
    ]
